import { readFileSync, readdirSync } from "fs";
import { join } from "path";

import { AVAILABLE_COMMANDS } from "./commands";
import {
  DEFAULT_ACTION_MAX_DIFF_SIZE,
  DEFAULT_MAX_COMMENTS,
  resolveMaxComments,
  resolveMaxDiffSize,
} from "./repo-config";

const repoRoot = join(__dirname, "..");
const reviewWorkflow = readFileSync(
  join(repoRoot, ".github", "workflows", "review.yml"),
  "utf8",
);
const selfTestWorkflow = readFileSync(
  join(repoRoot, ".github", "workflows", "self-test.yml"),
  "utf8",
);
const robinTemplate = readFileSync(join(repoRoot, "templates", "robin.yml"), "utf8");
const readme = readFileSync(join(repoRoot, "README.md"), "utf8");
const advancedDocs = readFileSync(join(repoRoot, "docs", "ADVANCED.md"), "utf8");
const actionYml = readFileSync(join(repoRoot, "action.yml"), "utf8");

const slashCommandGate =
  "startsWith(github.event.comment.body, '/robin')";

/** Inputs that are secrets / token on the action, not workflow_call inputs. */
const ACTION_ONLY_SECRETS = new Set([
  "github-token",
  "llm-api-key",
  "llm-base-url",
  "model",
]);

/** Workflow-only input (not an action input). */
const WORKFLOW_ONLY_INPUTS = new Set(["runner"]);

/**
 * Defer-to-config knobs must not force a boolean default of true/false on the
 * reusable workflow — that would override `.github/robin.yml`.
 * - request-changes: boolean, no default (omit → empty → repo config)
 * - use-json-response-mode: string, default ""
 */
const DEFER_BOOLEAN_NO_DEFAULT = ["request-changes"] as const;
const DEFER_STRING_EMPTY_DEFAULT = [
  "use-json-response-mode",
  "llm-max-attempts",
  // llm-max-relaunches 空值 ≠ 0：空表示"用 action 默认的 2"，0 表示"彻底不重启"。
  // 若在 workflow 上强行给 0，action.yml 里的 default 就永远到不了。
  "llm-max-relaunches",
] as const;

function parseActionInputs(source: string): string[] {
  // Scope to the inputs: section so a future outputs: block cannot pollute parity.
  const inputsBlock = source
    .split(/^inputs:\n/m)[1]
    ?.split(/^(?:outputs|runs|branding):/m)[0];
  if (!inputsBlock) return [];
  return [...inputsBlock.matchAll(/^  ([a-z0-9-]+):\n    description:/gm)].map(
    (match) => match[1],
  );
}

function publicActionInputs(): string[] {
  return parseActionInputs(actionYml).filter((name) => !ACTION_ONLY_SECRETS.has(name));
}

/** Keys under `on.workflow_call.inputs` (4-space indent under `inputs:`). */
function workflowCallInputNames(source: string): string[] {
  const callSection = source.split(/\n\s+secrets:\n/)[0] ?? source;
  const inputsBlock = callSection.split(/\n\s+inputs:\n/)[1];
  if (!inputsBlock) return [];
  return [...inputsBlock.matchAll(/^      ([a-z0-9-]+):\n/gm)].map((match) => match[1]);
}

/**
 * Collect `key:` names from a YAML mapping that starts after `with:`.
 * Skips blank lines and `#` comments so fixtures can document values.
 */
function mappingKeysAfterWith(source: string, withIndent: string): string[] {
  const marker = `\n${withIndent}with:\n`;
  const start = source.indexOf(marker);
  if (start < 0) return [];
  const body = source.slice(start + marker.length);
  const keyIndent = `${withIndent}  `;
  const keys: string[] = [];
  for (const line of body.split("\n")) {
    if (line.trim() === "" || line.trimStart().startsWith("#")) continue;
    if (!line.startsWith(keyIndent)) break;
    if (line.slice(keyIndent.length).startsWith(" ")) continue; // nested
    const match = line.slice(keyIndent.length).match(/^([a-z0-9-]+):/);
    if (match) keys.push(match[1]);
  }
  return keys;
}

/** `with:` keys on the Robin action step inside review.yml. */
function forwardedActionInputNames(source: string): string[] {
  return mappingKeysAfterWith(source, "        ").filter(
    (name) => !ACTION_ONLY_SECRETS.has(name),
  );
}

/** Top-level `with:` keys under the consumer job that calls the reusable workflow. */
function consumerWorkflowWithKeys(source: string): string[] {
  return mappingKeysAfterWith(source, "    ");
}

function workflowCallInputBlock(source: string, name: string): string | undefined {
  const callSection = source.split(/\n\s+secrets:\n/)[0] ?? source;
  const match = callSection.match(
    new RegExp(`^      ${name}:\\n((?:        [^\\n]*\\n)+)`, "m"),
  );
  return match?.[1];
}

describe("reusable review workflow", () => {
  it.each([
    ["review.yml", reviewWorkflow],
    ["self-test.yml", selfTestWorkflow],
  ])("accepts /robin comment triggers in %s", (_name, workflow) => {
    expect(workflow).toContain(slashCommandGate);
    expect(workflow).toContain("startsWith(github.event.comment.body, '/review')");
  });

  it("keeps the consumer template on the canonical reusable workflow", () => {
    expect(robinTemplate).toContain("Generated by robin-review");
    expect(robinTemplate).toContain(
      "uses: antongulin/robin/.github/workflows/review.yml@main",
    );
    expect(robinTemplate).toContain("types: [opened, reopened, ready_for_review]");
    expect(robinTemplate).toContain("actions: read");
    expect(robinTemplate).toContain("LLM_API_KEY: ${{ secrets.LLM_API_KEY }}");
    expect(robinTemplate).not.toContain("- uses: antongulin/robin@");
  });

  it("exposes every non-secret action input through workflow_call and forwards it", () => {
    const expected = [...publicActionInputs(), ...WORKFLOW_ONLY_INPUTS].sort();
    expect(workflowCallInputNames(reviewWorkflow).sort()).toEqual(expected);

    const forwarded = forwardedActionInputNames(reviewWorkflow).sort();
    expect(forwarded).toEqual(publicActionInputs().sort());

    for (const name of publicActionInputs()) {
      expect(reviewWorkflow).toContain(`${name}: \${{ inputs.${name} }}`);
    }
  });

  it("scopes action input parsing to the inputs section (ignores outputs)", () => {
    const synthetic = [
      "name: Test",
      "inputs:",
      "  fail-on-high:",
      "    description: Fail on high",
      "  request-changes:",
      "    description: Advisor mode",
      "outputs:",
      "  summary:",
      "    description: Review summary",
      "runs:",
      "  using: node24",
      "",
    ].join("\n");
    expect(parseActionInputs(synthetic)).toEqual([
      "fail-on-high",
      "request-changes",
    ]);
  });

  it("keeps defer-to-config knobs from forcing a boolean default", () => {
    for (const name of DEFER_BOOLEAN_NO_DEFAULT) {
      const block = workflowCallInputBlock(reviewWorkflow, name);
      expect(block).toBeDefined();
      expect(block).toContain("type: boolean");
      // Ignore comments that mention "default"; only a real YAML key would break deferral.
      expect(block).not.toMatch(/^\s*default:/m);
    }
    for (const name of DEFER_STRING_EMPTY_DEFAULT) {
      const block = workflowCallInputBlock(reviewWorkflow, name);
      expect(block).toBeDefined();
      expect(block).toContain("type: string");
      expect(block).toContain('default: ""');
    }
  });

  it("documents every public action input in ADVANCED.md", () => {
    for (const name of publicActionInputs()) {
      expect(advancedDocs).toContain(`\`${name}\``);
    }
  });

  it("exposes only reasoning-effort as a reasoning setting", () => {
    expect(publicActionInputs().filter((name) => name.includes("reasoning"))).toEqual([
      "reasoning-effort",
    ]);
    expect(actionYml).not.toContain("reasoning-exclude");
    expect(reviewWorkflow).not.toContain("reasoning-exclude");
  });

  it("documents reasoning-effort config precedence and its unsupported-parameter fallback", () => {
    expect(advancedDocs).toContain("### Reasoning effort (provider-dependent)");
    expect(advancedDocs).toContain("reasoning-effort: high");
    expect(advancedDocs).toContain(".github/robin.yml");
    expect(advancedDocs).toContain("400/422");
    expect(readme).toContain("reasoning-effort");
  });

  it("keeps a consumer fixture that exercises every workflow_call input", () => {
    const fixtureDir = join(repoRoot, "testdata", "consumer-workflows");
    const fixtures = readdirSync(fixtureDir).filter((name) => name.endsWith(".yml"));
    expect(fixtures).toContain("all-inputs.yml");

    const fixture = readFileSync(join(fixtureDir, "all-inputs.yml"), "utf8");
    expect(consumerWorkflowWithKeys(fixture).sort()).toEqual(
      workflowCallInputNames(reviewWorkflow).sort(),
    );
  });

  it("lets callers choose a GitHub-hosted or self-hosted runner", () => {
    expect(reviewWorkflow).toContain("runner:");
    expect(reviewWorkflow).toContain(
      'description: "Runner label or JSON array of labels to use for the review job."',
    );
    expect(reviewWorkflow).toContain("default: '\"ubuntu-latest\"'");
    expect(reviewWorkflow).toContain("runs-on: ${{ fromJSON(inputs.runner) }}");
  });

  it("documents local and Coolify self-hosted runner usage", () => {
    expect(readme).toContain("## Running on a self-hosted runner");
    expect(readme).toContain("runner: '[\"self-hosted\", \"local\"]'");
    expect(readme).toContain(
      "runner: '[\"self-hosted\", \"linux\", \"coolify\"]'",
    );
    expect(readme).toContain("runner: '\"ubuntu-latest\"'");
    expect(readme).toContain(
      "Self-hosted runners can execute arbitrary workflow code.",
    );
    expect(readme).toContain(
      "Repository Settings -> Actions -> Runners -> New self-hosted runner",
    );
    expect(readme).toContain(
      "A matching self-hosted runner must be online when GitHub starts the review job.",
    );
    expect(readme).toContain(
      "Docker is optional; it is just one way to run the GitHub Actions runner.",
    );
    expect(readme).toContain(
      "If no matching runner is online, GitHub queues the job until one comes online.",
    );
  });
});

/**
 * R943：`review.yml` 的 job-if 里还有**第四份**命令清单。
 *
 * `AVAILABLE_COMMANDS`（权威）、`parseSlashCommand` 的正则、`/help` 的表格，
 * 三份都在 `src/` 里，本轮把前两份归一了；但 `review.yml:123-126` 用
 * `startsWith(github.event.comment.body, '/review') || ...` 又硬编码了一组。
 *
 * 这一份最危险：它是 job-if，**命令写漏了就不会起 run** —— 用户敲了命令、
 * `/help` 里也列着、action 内部也认得，但整个 workflow 根本不触发，
 * 而没有任何报错能指出「命令清单漏了一条」。
 *
 * 所以把它钉到清单上。这里已有先例（`documents every public action input in
 * ADVANCED.md`、`keeps the consumer template on the canonical reusable workflow`），
 * 都是同一类跨文件一致性断言。
 */
describe("job-if 与命令清单一致", () => {
  const jobIfCommand = (text: string): string[] =>
    Array.from(
      text.matchAll(/github\.event\.comment\.body[^)]*?['"](\/[a-z][a-z0-9-]*)['"]/g),
      (m) => m[1]
    );

  const fromList = AVAILABLE_COMMANDS.map((c) => c.command).sort();

  // `review.yml` 和 `self-test.yml` 两份 job-if 都得跟着清单走。
  // `self-test.yml` 的 `command-test` job 尤其关键：它是仓库自己的 e2e，
  // job-if 一旦漏写命令，对应的 e2e 场景就**永远不会执行** ——
  // 不报错、不失败，只是安静地不再测任何东西。
  it.each([
    ["review.yml", reviewWorkflow],
    ["self-test.yml", selfTestWorkflow],
  ])("%s 的 job-if 覆盖的正是清单里的每一个命令（不多不少）", (_name, workflow) => {
    expect([...new Set(jobIfCommand(workflow))].sort()).toEqual(fromList);
  });

  it.each([
    ["review.yml", reviewWorkflow],
    ["self-test.yml", selfTestWorkflow],
  ])("%s 的 job-if 里清单每条命令都真的出现过（漏写 = 命令静默不触发）", (_name, workflow) => {
    const listedInJobIf = jobIfCommand(workflow);
    for (const command of fromList) {
      expect(listedInJobIf).toContain(command);
    }
  });
});

/**
 * R946：「未设置」哨兵的同一份真相有**五份副本**，改一处忘另一处就静默失效。
 *
 * `resolveMaxComments` / `resolveMaxDiffSize` 判断「调用方是否真的没传」的方式是
 * 「解析结果是否等于默认常量」（见 repo-config.ts 的 isUnset）。这条哨兵必须在下面
 * 五处逐字相等：
 *
 *   1. `repo-config.ts` 的常量
 *   2. `action.yml` 的 input default
 *   3. `.github/workflows/review.yml` 的 input default
 *   4. `main.ts` 里 `getInput(...) || <兜底>` 的兜底
 *   5. `docs/ADVANCED.md` 里写给人看的说明
 *
 * 只要有一处漂移，后果**不是报错而是无声降级**：哨兵不再等值 ⇒ 解析结果被当成
 * 「调用方显式传了」⇒ `.github/robin.yml` 的配置被完全忽略，没有任何日志。
 *
 * 本轮实测到的实例：`main.ts` 里 `max-comments` 的兜底写的是字面量 `"25"`，
 * 而常量是 15。`"25"` 恰好等于 `action.yml` 之外的旧默认值，一眼看不出来。
 */
describe("「未设置」哨兵：五份副本必须逐字相等（R946）", () => {
  const mainSrc = readFileSync(join(repoRoot, "src", "main.ts"), "utf8");
  // 剥注释：注释里会解释「这是哨兵」，里面必然出现数字，直接搜会被注释骗过。
  const mainCode = mainSrc
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^[ \t]*\/\/.*$/gm, "");

  /** 取 YAML 里某个 input 的 default（带引号原样返回）。缩进自适应。 */
  function inputDefault(source: string, name: string): string | undefined {
    const key = new RegExp(`^([ \\t]+)${name}:[ \\t]*$`, "m").exec(source);
    if (!key) return undefined;
    const indent = key[1].length;
    const rest = source.slice(key.index + key[0].length);
    let block = "";
    for (const line of rest.split("\n")) {
      if (line.trim() === "") {
        block += "\n";
        continue;
      }
      if ((line.match(/^[ \t]*/) as RegExpMatchArray)[0].length <= indent) break;
      block += `${line}\n`;
    }
    return block.match(/^[ \t]+default:[ \t]*"?([^"\n]*)"?[ \t]*$/m)?.[1];
  }

  /** 取 main.ts 里 `core.getInput("x") || <兜底>` 的兜底表达式原文。 */
  function mainFallback(name: string): string {
    const m = new RegExp(`core\\.getInput\\("${name}"\\)\\s*\\|\\|\\s*(.+?);`).exec(mainCode);
    expect(m).not.toBeNull();
    return (m as RegExpMatchArray)[1].trim();
  }

  /**
   * 判据分两层，这里是第一层（值相等）：
   * 兜底要么引用正确的常量，要么是个与常量**等值**的字面量。
   *
   * 第二层在下面（「不再用裸数字兜底」）**禁止任何字面量**，比这一层更严。
   * 第一层单独存在时会放过 `|| "15"`，实测（M36）真正报红的是第二层。
   * 两层都要：第二层防的是「同一份真相被复制成第六份」，第一层防的是
   * 「引用了错的常量」——后者第二层看不见（`String(别的常量)` 不是字面量）。
   */
  function expectFallbackMeans(name: string, constName: string, value: number) {
    const expr = mainFallback(name);
    const asLiteral = /^["'`](\d+)["'`]$/.exec(expr);
    if (asLiteral) {
      expect({ knob: name, fallback: expr }).toEqual({ knob: name, fallback: String(value) });
    } else {
      expect(expr).toBe(`String(${constName})`);
    }
  }

  it.each([
    ["max-comments", "DEFAULT_MAX_COMMENTS", DEFAULT_MAX_COMMENTS],
    ["max-diff-size", "DEFAULT_ACTION_MAX_DIFF_SIZE", DEFAULT_ACTION_MAX_DIFF_SIZE],
  ])("%s：action.yml 与 review.yml 的 default 都等于常量", (name, _constName, value) => {
    const want = String(value);
    expect({ where: "action.yml", got: inputDefault(actionYml, name) }).toEqual({
      where: "action.yml",
      got: want,
    });
    expect({ where: "review.yml", got: inputDefault(reviewWorkflow, name) }).toEqual({
      where: "review.yml",
      got: want,
    });
  });

  it.each([
    ["max-comments", "DEFAULT_MAX_COMMENTS", DEFAULT_MAX_COMMENTS],
    ["max-diff-size", "DEFAULT_ACTION_MAX_DIFF_SIZE", DEFAULT_ACTION_MAX_DIFF_SIZE],
  ])("%s：main.ts 的兜底表达的就是这个默认值", (name, constName, value) => {
    expectFallbackMeans(name, constName, value);
  });

  it("main.ts 里这两个 input 不再用裸数字兜底（避免同一份真相再被复制）", () => {
    // 精确匹配 `|| <裸数字字面量>`，不误伤 `|| ""` 这类语义不同的兜底。
    expect(mainCode).not.toMatch(/getInput\("(?:max-comments|max-diff-size)"\)\s*\|\|\s*["'`]\d+["'`]/);
    // 已知上限（不假装完备）：这是**正则判据**，有构造性输入上限。
    // `|| String(15)` / `|| (15).toString()` 能绕过它，而那仍是把常量复制了一份。
    // 要语义级得编译 main.ts 求值 —— 代价过高，本轮不做，改为如实标注。
  });

  it("哨兵真的能让 repo 配置赢：空输入 + repo 有值 ⇒ 取 repo 的值", () => {
    // 这是哨兵存在的**理由**。若哪天改成别的判定方式，下面两条会红，
    // 而那时「action default 等于常量」这条相等性本身未必察觉得到。
    expect(resolveMaxComments(String(DEFAULT_MAX_COMMENTS), { maxComments: 8 })).toBe(8);
    expect(resolveMaxDiffSize(String(DEFAULT_ACTION_MAX_DIFF_SIZE), { maxDiffSize: 9 })).toBe(9);
  });

  it("docs/ADVANCED.md 写给人的默认值也等于常量（文档漂移同样是静默降级）", () => {
    for (const line of advancedDocs.split("\n")) {
      // 只看明确介绍这两个 knob 默认值的表格行：`| `max-comments` | `15` | ...`
      const m = /^\|\s*`(max-comments|max-diff-size)`\s*\|\s*`?(\d+)`?\s*\|/.exec(line);
      if (!m) continue;
      const expected =
        m[1] === "max-comments" ? String(DEFAULT_MAX_COMMENTS) : String(DEFAULT_ACTION_MAX_DIFF_SIZE);
      expect({ knob: m[1], documented: m[2] }).toEqual({ knob: m[1], documented: expected });
    }
  });
});
